"""
This type stub file was generated by pyright.
"""

pyfmodex = ...

def import_pyfmodex(): ...
def extract_audioclip_samples(audio) -> dict:
    """extracts all the samples from an AudioClip
    :param audio: AudioClip
    :type audio: AudioClip
    :return: {filename : sample(bytes)}
    :rtype: dict
    """
    ...

def dump_samples(clip): ...
def subsound_to_wav(subsound): ...
