"""
This type stub file was generated by pyright.
"""

from ..classes import Material, Renderer

def get_mesh(meshR: Renderer): ...
def export_mesh_renderer(obj: Renderer, export_dir: str) -> None: ...
def export_material(mat: Material) -> str:
    """Creates a material file (.mtl) for the given material."""
    ...
