"""
This type stub file was generated by pyright.
"""

from UnityPy.classes import Mesh

def export_mesh(m_Mesh: Mesh, format=...) -> str: ...
def export_mesh_obj(m_Mesh, material_names: list = ...): ...
