"""
This type stub file was generated by pyright.
"""

from PIL import Image

def get_image(sprite, texture, alpha_texture) -> Image.Image: ...
def get_image_from_sprite(m_Sprite) -> Image.Image: ...
def get_triangles(m_Sprite):  # -> list[list[tuple[Unknown, Unknown]]]:
    """
    returns the triangles of the sprite polygon
    """
    ...
