"""
This type stub file was generated by pyright.
"""

from .RuntimeAnimatorController import RuntimeAnimatorController

class AnimationClipOverride:
    def __init__(self, reader) -> None: ...

class AnimatorOverrideController(RuntimeAnimatorController):
    def __init__(self, reader) -> None: ...
