"""
This type stub file was generated by pyright.
"""

from .NamedObject import NamedObject

class AssetInfo:
    def __init__(self, reader) -> None: ...

class AssetBundle(NamedObject):
    def __init__(self, reader) -> None: ...
