"""
This type stub file was generated by pyright.
"""

from .NamedObject import NamedObject

class AudioClip(NamedObject):
    def __init__(self, reader) -> None: ...
    @property
    def extension(self): ...
    @property
    def samples(self) -> dict: ...
