"""
This type stub file was generated by pyright.
"""

from .Component import Component
from ..streams import EndianBinaryReader, EndianBinaryWriter

class Behaviour(Component):
    def __init__(self, reader: EndianBinaryReader) -> None: ...
    def save(self, writer: EndianBinaryWriter = ...): ...
