"""
This type stub file was generated by pyright.
"""

from .EditorExtension import EditorExtension
from .PPtr import PPtr

class GameObject(EditorExtension):
    m_Components: list
    m_Layer: int
    name: str
    m_Animator: PPtr
    m_Animation: PPtr
    m_Transform: PPtr
    m_MeshRenderer: PPtr
    m_SkinnedMeshRender: PPtr
    m_MeshFilter: PPtr
    def __init__(self, reader) -> None: ...
