"""
This type stub file was generated by pyright.
"""

from .NamedObject import NamedObject
from . import PPtr, Shader, Texture

class Material(NamedObject):
    m_Shader: PPtr[Shader]
    def __init__(self, reader) -> None: ...

class UnityTexEnv:
    m_Texture: PPtr[Texture]
    def __init__(self, reader) -> None: ...

class UnityPropertySheet:
    def __init__(self, reader) -> None: ...
