"""
This type stub file was generated by pyright.
"""

from .NamedObject import NamedObject

class Material(NamedObject):
    def __init__(self, reader) -> None: ...

class UnityTexEnv:
    def __init__(self, reader) -> None: ...

class UnityPropertySheet:
    def __init__(self, reader) -> None: ...
