"""
This type stub file was generated by pyright.
"""

from .Component import Component
from . import Mesh, PPtr

class MeshFilter(Component):
    m_Mesh: PPtr[Mesh]
    def __init__(self, reader) -> None: ...
