"""
This type stub file was generated by pyright.
"""

from .Behaviour import Behaviour
from ..streams import EndianBinaryReader, EndianBinaryWriter

class MonoBehaviour(Behaviour):
    def __init__(self, reader: EndianBinaryReader) -> None: ...
    def save(self, writer: EndianBinaryWriter = ..., raw_data: bytes = ...): ...
    @property
    def raw_data(self) -> bytes:
        """
        Reads the undocumentated data following the default init.
        This is usefull for classes that are stored via MonoBehaviours.
        """
        ...
