"""
This type stub file was generated by pyright.
"""

from .Component import Component

class StaticBatchInfo:
    def __init__(self, reader) -> None: ...

class Renderer(Component):
    def __init__(self, reader) -> None: ...
    def export(self, export_dir: str) -> None: ...
