"""
This type stub file was generated by pyright.
"""

from typing import List
from . import Component, GameObject, Material, PPtr, Transform

class StaticBatchInfo:
    def __init__(self, reader) -> None: ...

class Renderer(Component):
    m_Materials: List[PPtr[Material]]
    m_StaticBatchRoot: PPtr[Transform]
    m_ProbeAnchor: PPtr[Transform]
    m_LightProbeVolumeOverride: PPtr[GameObject]
    m_LightProbeAnchor: PPtr[Transform]
    def __init__(self, reader) -> None: ...
    def export(self, export_dir: str) -> None: ...
