"""
This type stub file was generated by pyright.
"""

from .Object import Object
from ..streams import EndianBinaryWriter

class ResourceManager(Object):
    def __init__(self, reader) -> None: ...
    def save(self, writer: EndianBinaryWriter = ...): ...
