"""
This type stub file was generated by pyright.
"""

from typing import Any, List
from . import Animation, Mesh, PPtr, Renderer

class SkinnedMeshRenderer(Renderer):
    m_Quality: int
    m_UpdateWhenOffscreen: bool
    m_SkinNormals: bool
    m_DisableAnimationWhenOffscreen: PPtr[Animation]
    m_Mesh: PPtr[Mesh]
    m_BonesSize: int
    m_Bones: PPtr[Any]
    m_BlendShapeWeights: List[float]
    def __init__(self, reader) -> None: ...
