"""
This type stub file was generated by pyright.
"""

from .NamedObject import NamedObject

class SpriteAtlas(NamedObject):
    def __init__(self, reader) -> None: ...

class SpriteAtlasData:
    def __init__(self, reader) -> None: ...
