"""
This type stub file was generated by pyright.
"""

from .NamedObject import NamedObject
from ..streams import EndianBinaryWriter

class Texture(NamedObject):
    def __init__(self, reader) -> None: ...
    def save(self, writer: EndianBinaryWriter): ...
